// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-pqvVhjX2nRCc-YuT4404Ncuprdh_y30',
    appId: '1:416112167372:web:44e26d536d32ecc079b569',
    messagingSenderId: '416112167372',
    projectId: 'reddit-55762',
    authDomain: 'reddit-55762.firebaseapp.com',
    storageBucket: 'reddit-55762.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRd_C5HsLfoIDkn7tmFHNKoDQj-gonOsM',
    appId: '1:416112167372:android:2e3415216b20a93b79b569',
    messagingSenderId: '416112167372',
    projectId: 'reddit-55762',
    storageBucket: 'reddit-55762.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALzNX6I2XPBh6c4O8s-RJtORj4csW1Bzs',
    appId: '1:416112167372:ios:93938e8c0b1e542379b569',
    messagingSenderId: '416112167372',
    projectId: 'reddit-55762',
    storageBucket: 'reddit-55762.firebasestorage.app',
    iosBundleId: 'com.example.reddit',
  );
}
